### ISSUE TITLE
ViT feature extraction code

### ISSUE THREAD

**Issue by heyzude** [cshizhe/VLN-DUET#10]
Hi, and thanks for your great work and for sharing it with us :)

I wonder if you could also share the code used for extracting image features from ViT.

I also wonder what folder you extracted features from. There are `undistorted_color_images`,  `matterport_color_images`, and `matterport_skybox_images` folders for each scan.

Thanks!

**Comment by cshizhe** [comment]
Hi, the images are rendered with the [Matterport3DSimulator](https://github.com/peteanderson80/Matterport3DSimulator) which uses the matterport_skybox_images folder.
Check [this](https://github.com/cshizhe/HM3DAutoVLN/blob/main/hm3d_data_gen/step02_extract_view_features.py) for feature extraction codes.

**Comment by DITINGmisa** [comment]
Hello, thanks for your great work！
I noticed that the output in ViT features 197x768 and 197x1000 for each image, how does your code convert this to the 1x1768 format in the file you provided?
