### ISSUE TITLE
Some weights of GlocalTextPathCMTPreTraining were not initialized from the model checkpoint at None and are newly initialized: 

### ISSUE THREAD

**Issue by Hoyyyaard** [cshizhe/VLN-DUET#11]
When I apply pretrain model to the code of finetune it showed some notice：

Some weights of GlocalTextPathCMTPreTraining were not initialized from the model checkpoint at None and are newly initialized: ['bert.img_embeddings.img_layer_norm.bias', 'bert.img_embeddings.pano_encoder.layers.1.linear2.weight', 'bert.img_embeddings.img_linear.weight', 'bert.img_embeddings.img_layer_norm.weight', 'global_sap_head.net.0.weight', 'bert.img_embeddings.pano_encoder.layers.0.norm2.bias', 'bert.img_embeddings.pano_encoder.layers.0.norm2.weight', 'local_sap_head.net.2.bias', 'bert.img_embeddings.pano_encoder.layers.0.linear2.weight', 'bert.img_embeddings.nav_type_embedding.weight', 'bert.img_embeddings.loc_linear.weight', 'bert.img_embeddings.loc_layer_norm.weight', 'sap_fuse_linear.net.3.weight', 'bert.img_embeddings.pano_encoder.norm.weight', 'bert.img_embeddings.pano_encoder.layers.1.linear1.weight', 'local_sap_head.net.0.bias', 'bert.insobj_embeddings.insobj_linear.bias', 'image_classifier.net.2.bias', 'bert.img_embeddings.pano_encoder.layers.0.linear1.weight', 'bert.global_encoder.sprel_linear.weight', 'bert.img_embeddings.loc_layer_norm.bias', 'bert.img_embeddings.pano_encoder.layers.1.self_attn.out_proj.bias', 'sap_fuse_linear.net.3.bias', 'bert.img_embeddings.pano_encoder.layers.1.norm1.bias', 'bert.img_embeddings.pano_encoder.layers.0.linear1.bias', 'bert.img_embeddings.pano_encoder.layers.0.linear2.bias', 'bert.local_encoder.vp_pos_embeddings.1.weight', 'global_sap_head.net.3.weight', 'bert.img_embeddings.pano_encoder.layers.1.norm1.weight', 'bert.global_encoder.gmap_pos_embeddings.1.weight', 'bert.img_embeddings.pano_encoder.layers.0.self_attn.out_proj.bias', 'image_classifier.net.0.bias', 'image_classifier.net.3.weight', 'bert.img_embeddings.layer_norm.weight', 'local_sap_head.net.3.weight', 'bert.img_embeddings.pano_encoder.layers.1.self_attn.in_proj_weight', 'bert.img_embeddings.loc_linear.bias', 'bert.global_encoder.gmap_pos_embeddings.0.weight', 'bert.insobj_embeddings.insobj_layer_norm.bias', 'image_classifier.net.3.bias', 'bert.img_embeddings.pano_encoder.norm.bias', 'bert.img_embeddings.pano_encoder.layers.0.norm1.bias', 'bert.insobj_embeddings.insobj_layer_norm.weight', 'bert.global_encoder.gmap_pos_embeddings.1.bias', 'bert.local_encoder.vp_pos_embeddings.1.bias', 'bert.global_encoder.sprel_linear.bias', 'bert.img_embeddings.pano_encoder.layers.0.norm1.weight', 'bert.img_embeddings.pano_encoder.layers.1.linear1.bias', 'bert.img_embeddings.pano_encoder.layers.1.norm2.bias', 'local_sap_head.net.3.bias', 'bert.local_encoder.vp_pos_embeddings.0.bias', 'bert.img_embeddings.layer_norm.bias', 'bert.global_encoder.gmap_pos_embeddings.0.bias', 'bert.img_embeddings.pano_encoder.layers.1.self_attn.in_proj_bias', 'sap_fuse_linear.net.2.bias', 'bert.img_embeddings.pano_encoder.layers.1.linear2.bias', 'local_sap_head.net.2.weight', 'global_sap_head.net.0.bias', 'sap_fuse_linear.net.0.weight', 'bert.img_embeddings.pano_encoder.layers.1.norm2.weight', 'bert.img_embeddings.pano_encoder.layers.1.self_attn.out_proj.weight', 'bert.global_encoder.gmap_step_embeddings.weight', 'local_sap_head.net.0.weight', 'bert.img_embeddings.pano_encoder.layers.0.self_attn.in_proj_weight', 'global_sap_head.net.3.bias', 'sap_fuse_linear.net.2.weight', 'bert.img_embeddings.pano_encoder.layers.0.self_attn.out_proj.weight', 'bert.insobj_embeddings.insobj_linear.weight', 'bert.img_embeddings.img_linear.bias', 'sap_fuse_linear.net.0.bias', 'global_sap_head.net.2.weight', 'image_classifier.net.0.weight', 'image_classifier.net.2.weight', 'global_sap_head.net.2.bias', 'bert.local_encoder.vp_pos_embeddings.0.weight', 'bert.img_embeddings.pano_encoder.layers.0.self_attn.in_proj_bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Is this problem normal?

**Comment by heyzude** [comment]
Yes. It's because there are parameters that LXMERT does not have. You're trying to initialize GlocalTextPathCMTPreTraining with LXMERT, and some parameters of GlocalTextPathCMTPreTraining are not in LXMERT.
