### ISSUE TITLE
Val-unseen SR&SPL in pretrain and finetune

### ISSUE THREAD

**Issue by Hoyyyaard** [cshizhe/VLN-DUET#12]
Hello，When I apply the official code for pretrain ，the val-unseen sr is about 48 of the best ckpt；
Then I apply this ckpt to the finetune code ， it easily reach about 65 of val-unseen sr after epoch 20000，but the val-unseen sr does not raise obviously at the rest of the finetune process;
We cannot reproduce the val-unseen eval standrd in the paper and we do not know which part  went wrong.Can u please inform us  some information?

**Comment by cshizhe** [comment]
How do you select the best checkpoint? It seems to be a similar issue as [this](https://github.com/cshizhe/VLN-DUET/issues/13).

**Comment by Hoyyyaard** [comment]
I run an online testing with the pretained ckpts and select the checkpoint with highest navigation performance too; Can you please inform us the sr and spl of your best pretrained ckpts? Thanks!

**Comment by MarSaKi** [comment]
> I run an online testing with the pretained ckpts and select the checkpoint with highest navigation performance too; Can you please inform us the sr and spl of your best pretrained ckpts? Thanks!

I guess it is informed in the Table.3 of the mainpaper.

**Comment by Hoyyyaard** [comment]
Sorry， I forgot to emphasize  that this data was ran on R2R
