### ISSUE TITLE
action_step vs step

### ISSUE THREAD

**Issue by TikaToka** [cshizhe/VLN-DUET#22]
Hello cshize, thank you for sharing your work.

I am using your model, and I want to know the difference between action_step and step in evaluation result.

Thank you in advance, and have a nice day!

regards.

**Comment by cshizhe** [comment]
Hi, as shown in the code [here](https://github.com/cshizhe/VLN-DUET/blob/93e8b233164bc079a6db48b8a0a78d123ec8de41/map_nav_src/r2r/env.py#L360), action_step denotes the number of local actions from one node to another, while step denotes the number of predicted global actions.
