### ISSUE TITLE
No module named 'MatterSim'

### ISSUE THREAD

**Issue by Breezewrf** [cshizhe/VLN-DUET#23]
Hi,

Thank you for your excellent work.

I am trying to run the scripts/run_reverie.sh, but meet with the error: No module named 'MatterSim'. 

I have finished the installation of Matterport Simulator,and export PYTHONPATH=/home/breeze/Desktop/workplace/Matterport3DSimulator/build:$PYTHONPATH. But the MatterSim seems can not be imported directly, should I move the project into the docker which contain the MatterSim?

Thank you!

**Comment by Breezewrf** [comment]
I think the problem has been figured out.

Here is my solution:
1. Maybe the key is the python version. In fact, it seems we can only use python < 3.7 in order to run the MatterSim. 
2. `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/breeze/Desktop/workplace/Matterport3DSimulator/build`
3. Use `cp $(find / -name "libjson-c.so.3")` to copy all the .so file omitted to the `build` folder when you try to import MatterSim
4. `import sys` `sys.path.insert(0, '/home/breeze/Desktop/workplace/Matterport3DSimulator/build')` before you import MatterSim

Hope helpful for others.

**Comment by JL-sky** [comment]
> I think the problem has been figured out.
> 
> Here is my solution:
> 
> 1. Maybe the key is the python version. In fact, it seems we can only use python < 3.7 in order to run the MatterSim.
> 2. `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/breeze/Desktop/workplace/Matterport3DSimulator/build`
> 3. Use `cp $(find / -name "libjson-c.so.3")` to copy all the .so file omitted to the `build` folder when you try to import MatterSim
> 4. `import sys` `sys.path.insert(0, '/home/breeze/Desktop/workplace/Matterport3DSimulator/build')` before you import MatterSim
> 
> Hope helpful for others.

Hello, I have encountered exactly the same problem as you, but when I solved it according to your method, I could not find the file named libjson-c.so.3, may I ask if this file comes with the system or where you got it

**Comment by JL-sky** [comment]
> > I think the problem has been figured out.
> > Here is my solution:
> > 
> > 1. Maybe the key is the python version. In fact, it seems we can only use python < 3.7 in order to run the MatterSim.
> > 2. `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/breeze/Desktop/workplace/Matterport3DSimulator/build`
> > 3. Use `cp $(find / -name "libjson-c.so.3")` to copy all the .so file omitted to the `build` folder when you try to import MatterSim
> > 4. `import sys` `sys.path.insert(0, '/home/breeze/Desktop/workplace/Matterport3DSimulator/build')` before you import MatterSim
> > 
> > Hope helpful for others.
> 
> Hello, I have encountered exactly the same problem as you, but when I solved it according to your method, I could not find the file named libjson-c.so.3, may I ask if this file comes with the system or where you got it
你好，我遇到了和你完全一样的问题，我尝试过在docker里创建一个conda环境，但最后发现MatterSim只能通过python3.6才能import，然后我很幸运的看到你解决了这个问题，但是我并没有在我的系统里找到libjson-c.so.3这个文件，请问这个文件是系统自带的还是需要从哪里获得，另外请问你知道MatterSim是否有最新版本的
本人刚刚接触这个方向，有很多不了解的地方，还请多多指教

**Comment by JL-sky** [comment]
你好，我已经解决了，我修改了dockerfile文件，使用python3.8重新编译了MatterSim
