### ISSUE TITLE
URL of datasets is invailed https://www.dropbox.com/sh/u3lhng7t2gq36td/AABAIdFnJxhhCg2ItpAhMtUBa?dl=0

### ISSUE THREAD

**Issue by TLvCo** [cshizhe/VLN-DUET#25]
The link to download the dataset is invalid. Can you provide a new link

**Comment by cshizhe** [comment]
The link is fine. What problems do you encounter?

**Comment by TLvCo** [comment]
Sorry, I set the proxy rules incorrectly. The URL is valid, thank you very much for your reply!
