### ISSUE TITLE
The order of pano image

### ISSUE THREAD

**Issue by Hoyyyaard** [cshizhe/VLN-DUET#5]

**Comment by Hoyyyaard** [comment]
Hello， When I do some research I get access to the scanvp_candview_relangles.json file in R2R dataset Which record the relative position from one view point to another .It contains an info "[10, 0.1655278577578077, 0.1013200540255154, -0.13089583013280315]"where 10 stands for the view ids of current view point, But I'm confuse about  the order of the pano images .Could you tell me how the pano images generate?

**Comment by cshizhe** [comment]
See [here](https://github.com/cshizhe/VLN-DUET/blob/main/pretrain_src/data/dataset.py#L48).
