### ISSUE TITLE
How to generate that BBOX.json file ?

### ISSUE THREAD

**Issue by Mingxiao-Li** [cshizhe/VLN-DUET#8]
Hi, I am wondering how did you generate the BBOX.json file ? As I found this BBOX is different from the BBOX of both reverie data v1 and reverie data v2.

**Comment by cshizhe** [comment]
It is the same as the reverie data v1.

**Comment by cshizhe** [comment]
There is a slight different in SPL calculation where I take the length of provided path as groudtruth path  length while the official eval code uses the length of shortest path. But since most the provided paths are the shortest path, this doesn't have much influence on the results.

**Comment by Mingxiao-Li** [comment]
> There is a slight different in SPL calculation where I take the length of provided path as groudtruth path length while the official eval code uses the length of shortest path. But since most the provided paths are the shortest path, this doesn't have much influence on the results.

The biggest difference I got is the success rate and oracle success rate, while the RGS are the same. Did you get the same success rate ?

**Comment by cshizhe** [comment]
I got the same evaluation results before. What do you get? I guess the eval.ai may update the evaluation codes and use bbox v2.

**Comment by Mingxiao-Li** [comment]
I got a quite 5~8% lower in sr and osr in eval.ai. That is possible, but then it is impossible to get the test results on v1 version , which is bad. ~~

**Comment by cshizhe** [comment]
You could check with the authors of the reverie dataset to see if it is possible to get test results with v1 bboxes.

**Comment by Mingxiao-Li** [comment]
ok, thanks.
