### ISSUE TITLE
Question about pretraining

### ISSUE THREAD

**Issue by heyzude** [cshizhe/VLN-DUET#9]
Hi, thank you for opensourcing your work!

I have a question about pretraining phase.

I'm about to test Duet on R2R, but I wonder when you got the R2R performance on your paper, 
did you pretrain the Duet model not only on R2R dataset but also on R4R, or other tasks like REVERIE?

I guess pretraining not only on R2R but also on other tasks can boost up the Duet performance on R2R val_unseen split.

**Comment by cshizhe** [comment]
We only pretrained on R2R.
